### ISSUE TITLE
locaties met twee vegetatieopnames in verschillende jaren 

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#1]
Dit zorgt voor extra complexiteit omdat de verschillende bemonsteringen soms niet volledig consistent zijn (andere bedekkingen voor habitattypen). Ik neem daarom (voorlopig) enkel de eerste (oudste) vegetatieopname mee in de voortgangsanalyse.

**Comment by florisvdh** [comment]
OK
Bedoel je met "andere bedekkingen voor habitattypen" de verschillende phab volgens opeenvolgende versies van de habitatkaart?

**Comment by ToonHub** [comment]
Nee, verschillende waargenomen habitattypen op terrein. Sommige locaties bevatten meerdere meetpunten voor verschillende habitattypen (meerdere doelhabitattypen). Maar er kan natuurlijk maar een van die meetpunten weerhouden worden. Er zou dan maar een keer op terrein gegaan moeten worden voor  de verschillende meetpunten. Maar in enkele gevallen werd er één keer per meetpunt op terrein gegaan in verschillende jaren en kan het voorkomen dat de waargenomen habitattypen niet consistent zijn.
Ik bespreek het nog met Patrik.

**Comment by Patrikoosterlynck** [comment]
Heeft dus te maken met herbezoeken in functie van suboptimale omstandigheden tijdens de eerste opname (gemaaid of iets dergelijks...), ik moet de gevallen nog eens bekijken maar het lijkt me dat er steeds de meest recente meting dient weerhouden te worden en de oudere kunnen eigenlijk verwijderd worden.

**Comment by Patrikoosterlynck** [comment]
Toon kun je hier de betreffende gevallen nog eens toevoegen aub

**Comment by ToonHub** [comment]
@Patrikoosterlynck 
[check_different_dates.txt](https://github.com/inbo/n2khab-sample-admin/files/4387917/check_different_dates.txt)

**Comment by Patrikoosterlynck** [comment]
300649_6230_ha" 300649 "in situ assessment" 2016 TRUE FALSE 129117.9 214958.2 2
"300649_6230_hmo" 300649 "in situ assessment" 2017 TRUE FALSE 129117.6 214955.1 2

voor de hmo heb ik geen data in INBOVEG dus ik haal die er uit, is nooit ingevoerd wegens 
onbetrouwbaar (kort begraasd)


480306_6230_ha" 480306 "in situ assessment" 2016 TRUE TRUE 221339.5 175265.5 2
"480306_6230_hn" 480306 "in situ assessment" 2018 TRUE FALSE 221341.6 175374.1 2

de 2016 meting is geschrapt zowel in INBOVEG als in overzicht


783954_6230_ha" 783954 "in situ assessment" 2016 TRUE FALSE 239549.7 186670.2 2
"783954_6230_hn" 783954 "in situ assessment" 2017 TRUE FALSE 239549.6 186670.1 2

2016 meetpunt verwijderd uit overzicht, zat ook niet in INBOVEG

**Comment by Patrikoosterlynck** [comment]
ik bezorg dus een nieuw overzicht

**Comment by ToonHub** [comment]
OK in orde
