### ISSUE TITLE
Ontbrekende bedekking van vegetatietypes in INBOveg

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#10]
Voor sommige meetpunten is er niet voor elk geobserveerd vegetatietype een bedekking ingevoerd in INBOveg. Het gaat enkel om cirkelplots. Minder prioritair om te corrigeren voor meetnet habitatkwaliteit want in de vierkante plots is de bedekking wel steeds ingevoerd. Maar voeg hieronder toch de ontbrekende bedekkingen toe voor de volledigheid.

[check_type_cover.txt](https://github.com/inbo/n2khab-sample-admin/files/4403107/check_type_cover.txt)

**Comment by Patrikoosterlynck** [comment]
"1" "N2000meetnet_Grasland_BHM" "1409089" "circle" "NA% 91E0_meso + NA% 4010 + 38% 6230_hmo + NA% 9120" doelvegetatie is wel ingeschat
"2" "N2000meetnet_Grasland_BHM" "6792238" "circle" "NA% rbbms + 61% 6230_hn + NA% 3130 + NA% gh + NA% 9120" doelvegetatie is wel ingeschat
"3" "N2000meetnet_Grasland_BHM" "6770678" "circle" "NA% 91E0_meso + 80% 6230_hmo + NA% gh" doelvegetatie is wel ingeschat
"4" "N2000meetnet_Grasland_BHM" "7678913" "circle" "NA% rbbhc + NA% rbbmr + 62% 6410_mo" doelvegetatie is wel ingeschat
"5" "N2000meetnet_Grasland_BHM" "1715637" "circle" "NA% rbbzil + NA% gh + NA% 1330_hpr" OK AANGEPAST
"6" "N2000meetnet_Grasland_BHM" "1338805" "circle" "NA% rbbah + NA% rbbkam + 48% 1330_hpr"doelvegetatie is wel ingeschat
"7" "N2000meetnet_Grasland_BHM" "1936821" "circle" "NA% rbbah + NA% gh + 15% 1330_hpr"  doelvegetatie is wel ingeschat
"8" "N2000meetnet_Grasland_BHM" "1750129" "circle" "NA% 1330_hpr" ok aangepast
"9" "N2000meetnet_Grasland_BHM" "1461001" "circle" "NA% rbbkam + NA% rbbzil + NA% 6430_mr + 50% 1330_hpr" doelvegetatie is wel ingeschat
"10" "N2000meetnet_Grasland_BHM" "2637569" "circle" "84% 6230_hmo + NA% rbbmr + NA% 3130_na + NA% 9120" doelvegetatie is wel ingeschat
"11" "N2000meetnet_Moeras_BHM" "1498102" "circle" "NA% rbbms + NA% gh + 36% 7140_meso" doelvegetatie is wel ingeschat
"12" "N2000meetnet_Moeras_BHM" "1829622" "circle" "NA% rbbms + NA% 3150 + 78% 7140_meso" doelvegetatie is wel ingeschat

**Comment by Patrikoosterlynck** [comment]
Meestal betreft het het aandelen niet-doelvegetatie die niet zijn ingeschat, maar de doelvegetatie wel; In twee gevallen heb ik de data aangevuld

**Comment by Patrikoosterlynck** [comment]
Issue lijkt mij gesloten te kunnen worden

**Comment by ToonHub** [comment]
OK
