### ISSUE TITLE
Fieldmapdatabank heide+grasland: geen opnames van planningsjaar 1 tot 3

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#11]
In de meest recente fieldmapdatabank (FieldMapData_NA2000) vind ik geen opnames van planningsjaar 1 tot 3 terug. Staan die in andere databank?

**Comment by govaerle** [comment]
klopt, ik ging er van uit dat jullie de moederdatabank beheren en ik periodiek de nieuwe plots aanlever. Maar ik zal het nakijken!

**Comment by govaerle** [comment]
Toon, deze mag toch gesloten worden he?

**Comment by ToonHub** [comment]
Inderdaad. Is in orde.
