### ISSUE TITLE
punten die verschoven zijn over een grotere afstand dan 100 meter

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#12]
Ik dacht dat we bij verschuiven van punten maximaal binnen een straal van 100 meter bleven. Kleine afwijkingen hierop kunnen zich wel voordoen, maar bij sommige meetpunten wordt er een veel verdere vervanglocatie geselecteerd. Zie overzicht:

[check_position_change.txt](https://github.com/inbo/n2khab-sample-admin/files/4444816/check_position_change.txt)

**Comment by Patrikoosterlynck** [comment]
Hmm, potentieel problematisch volgens mij naar random steekproef toe, ik vermoed dat dit vooral subjectieve beslissingen zijn na een dag(en) met te weinig aangetroffen doelhabitat. Ik zou de punten met meer dan 110m afwijking uit de steekproef houden

**Comment by ToonHub** [comment]
OK om de afwijkingen van groter dan 110m uit de steekproef te houden.

**Comment by Patrikoosterlynck** [comment]
ook hier weer de vraag: ik zou deze punten liever niet uit INBOVEG halen, maar hoe duiden we dat ze niet weerhouden worden in de steekproef. Via jouw suggesties van een veld met 'pq opgenomen voor habitat X' of via nog iets bijkomend gezien het hier wel 'doelhabitat' betreft maar wegens protocolafwijking niet gebruikte meetpunten...

**Comment by ToonHub** [comment]
Opnames moeten inderdaad niet uit inboveg verwijderd worden, want mogelijks wel bruikbaar voor andere doeleinden.
De controle of een opname al dan niet wordt meegenomen voor een meetnet gebeurt buiten inboveg. Ik zal hiervoor een veld aanmaken in het overzichtsbestand. Dus in inboveg moet hiervoor geen extra veld voorzien worden.

**Comment by Patrikoosterlynck** [comment]
OK prima.
Ik denk r nu ook aan dat het belangrijk is om dit traceerbaar te houden. Dus dat het mogelijk moet zijn  om de set meetpunten die bij een analyse op tijdstip t is gebeurd te kunnen afleiden. Weet niet of dat momenteel in je R scripts voorzien/mogelijk is, maar anticiperend op bepaalde vragen/noden zal dit zeker nodig zijn.
