### ISSUE TITLE
meetpunten waarvoor wordt aangegeven dat ze niet werden verschoven, maar toch op andere locatie liggen

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#13]
Zie overzicht punten:

[check_position_change2.txt](https://github.com/inbo/n2khab-sample-admin/files/4444829/check_position_change2.txt)

Misschien moeten we een minimumafstand hanteren, die we als afwijking toelaten t.o.v. oorspronkelijke meetpuntcoördinaten.

**Comment by Patrikoosterlynck** [comment]
interessante oefening, en aandachtspunt voor in de toekomst.
De afwijkingen van 1-2 meter kan ik mij voorstellen zijn bewust niet aangeduid als 'verplaatst' maar hebben te maken met vermijden van heterogeniteit van de plot (bv. net op greppel, etc...) maar kunnen in de toekomst ook beter als 'verplaatst' worden geduid misschien?

de grotere afstanden heb ik geen andere verklaring dat de aanduiding 'verplaatst' foutief is, en ik zou die dan ook aanpassen in overzichtsbestand. OK voor jou, vooraleer ik doorvoer?

**Comment by ToonHub** [comment]
OK om de grotere afstanden aan te passen in overzichtsbestand.

Over de kleinere afwijkingen twijfel ik nog. Die verplaatsing heeft een andere oorzaak en er worden daarvoor andere regels gevolgd dan de verplaatsingen over grotere afstanden. Misschien aanduiden als 'lokaal verschoven' en daarvoor ook regels voorzien in het protocol?
