### ISSUE TITLE
ANB-meetpunten met dubbele opgemeten xy-coördinaten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#14]
In de tabel GPS_REF zijn er enkele meetpunten met 2 paar xy-coordinaten:

[check_coordinates_double.txt](https://github.com/inbo/n2khab-sample-admin/files/4448663/check_coordinates_double.txt)

**Comment by govaerle** [comment]
opgelost, 
reden :  2 * ingemeten (beide voor geen habitat plots) en 2 * een verkeerd label toegekend.
