### ISSUE TITLE
ANB-meetpunten waarvoor opgemeten locatie op meer dan 100 meter van oorspronkelijke locatie ligt

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#15]
Op basis van de opgemeten coördinaten in tabel GPS_REF heb ik de afstand berekend tot de oorspronkelijke meetpuntlocatie.  Voor een aantal meetpunten is de afstand groter dan 100m. Voor enkele gaat het om zeer grote afstanden en is er waarschijnlijk iets mis met de loctie_id (grts_ranking).
Zie overzicht:

[check_distance.txt](https://github.com/inbo/n2khab-sample-admin/files/4448682/check_distance.txt)

Zijn er meetpunten verschoven volgens het daarvoor opgemaakte protocol? Zo ja, is dat dan bijgehouden. Zie soms wel bij Remarks dat punt verlegd is, maar weet niet of dit systematisch is genoteerd..

**Comment by govaerle** [comment]
opgelost; ik dacht even dat een GPS jammer de oorzaak was (het waren bijna alle punten nabij Leopoldsburg en KLeine Brogel). Maar het kan net zo goed een fout op terrein geweest zijn. Een aantal punten was 'versprongen' (label van de vorige plot toegekend, wat een resem fouten op gang heeft getrokken).
Nu rechtgezet.
