### ISSUE TITLE
inbo-opnames voor 1330_pol en 1330_da

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#16]
Ik vond enkele opnames voor habitatsubtype 1330_pol en 1330_da. Het eerste volgen we niet op met een meetnet. Voor beide subtypes zijn er den ik ook andere structuurvariabelen nodig voor lsvi- bepaling.
[check_inbo_type.txt](https://github.com/inbo/n2khab-sample-admin/files/4450533/check_inbo_type.txt)

**Comment by Patrikoosterlynck** [comment]
De 1310 subtypes behoren inderdaad niet tot de steekproef 1330_hpr, het zijn zeekraalvegetaties, die in theorie niet hadden moeten opgemeten worden. Moeten we in inboveg een bijkomende notatie voorzien om een éénduidige selectie van plots per steekproeftype mogelijk te maken? bv. als je de plots voor 1330_hpr wil selecteren, hoe ga je dan te werk? via selectie op veld 'habitat'??

Die 2 6410plots hadden inderdaad ook nog problemen qua doelvegetatie maar zijn nu opgelost

**Comment by ToonHub** [comment]
Het zou inderdaad handig zijn als er innboveg een veld komt met het habitattype waarvoor de opname is uitgevoerd, dus het habitattype in het centrum van de plot. Nu baseer ik mij op het habitattype in de vierkante plot. Maar soms zijn er meerdere habitattypen genoteerd in het vierkante plot en  dan ga ik er van uit dat de opname gebeurt is voor het habitattype dat overeenkomt met het doelhabitat. Dus een veld met  'habitattype meetpunt' zou inderdaad zeer handig zijn.
