### ISSUE TITLE
opnamedatum in googlesheet komt niet overeen met die in INBOVEG

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#23]
Voor onderstaande punten komt de opnamedatum in de [google sheet](https://docs.google.com/spreadsheets/d/1WkGPPYTb1Xytg5kJeOSxLvt3PUdFjlpPb4rwYG9znys/edit#gid=0) niet overeen met die in INBOVEG. 

user_reference_inboveg	db_ref	type_target	assessment_date_googlesheet	assessment_date_inboveg	cover_description_inboveg
WZ_21	wz_21	2160	2020-09-21	2020-09-22	100% 2130_hd
1298609	1298609	2180	2020-09-17	2020-09-01	100% 2180
268341_2180	268341	2180	2020-09-15	2020-09-14	100% 2180
1060149_2180	1060149	2180	2020-09-15	2020-09-14	100% 2180
2057585	2057585	2120	2020-08-20	2020-07-20	100% 2130_hd
2018749	2018749	1330_hpr	2020-08-18	2020-10-15	100% 1330_hpr
2993589	2993589	1330_hpr	2020-08-18	2020-08-28	100% 1330_hpr
3010229	3010229	1330_hpr	2020-08-18	2020-08-21	100% 1330_hpr
3026357	3026357	1330_hpr	2020-08-18	2020-08-28	100% 1330_hpr
3046837	3046837	1330_hpr	2020-08-18	2020-08-28	100% 1330_hpr
2805181	2805181	1330_hpr	2020-08-18	2020-10-15	100% 1330_hpr
2809525	2809525	1330_hpr	2020-08-18	2020-08-21	100% 1330_hpr
dh_06	dh_06	2130_had	2020-07-25	2020-07-22	100% 2130_had
dh_16	dh_16	2190	2020-07-25	2020-07-22	100% 2190
67697	67697	2130_hd	2020-07-12	2020-07-10	100% 2160
67697	67697	2160	2020-07-12	2020-07-10	100% 2160
121525	121525	2120	2020-07-03	2020-07-02	100% 2120

**Comment by Patrikoosterlynck** [comment]
Oke Toon, issues resolved 
heb de datum 1-op-1 gemaakt
enkel de voor-en derde laatste lijn: daarvoor vind ik in mhq sheet en inboveg maar één record?

**Comment by ToonHub** [comment]
> enkel de voor-en derde laatste lijn: daarvoor vind ik in mhq sheet en inboveg maar één record?

Is inderdaad één record

Bedankt om aan te passen. Is in orde nu.
