### ISSUE TITLE
Cirkelplot en vierkante plot hebben verschillende user_reference

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#27]
- user_reference cirkelplot = 562353 en vierkante plot = 562353_2160 --> user_reference vierkante plot veranderen naar 562353
- user_reference cirkelplot = WZ_22 en vierkante plot =  WZ_22_2130-hd --> user_reference vierkante plot veranderen naar WZ_22

**Comment by Patrikoosterlynck** [comment]
oke aangepast

**Comment by ToonHub** [comment]
He Patrik. Je bent iets te snel geweest en hebt 56253_2160 veranderd naar WZ_22.
Dus:

- record met recording_givid = IV2021011813214975: user_reference veranderen van WZ_22 naar 562353
- record met user_reference = WZ_2130-hd: user_reference veranderen van WZ_22_2130-hd naar WZ_22

**Comment by Patrikoosterlynck** [comment]
oeps, nu zou dat in orde moeten zijn

**Comment by ToonHub** [comment]
OK
