### ISSUE TITLE
aanpassing in INBOVEG

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#29]
Nog enkele aanpassingen:

- IV2022051115125222 en IV2022051309464011: oppervlakte toevoegen (1018)
- IV2022032109305197 verwijderen (user reference = 8207669)
- plot 11686065 is dubbel ingevoerd (zowel cirkel als vierkante plot)
-  plot 4608177 is dubbel ingevoerd (zowel cirkel als vierkante plot), eenmaal als 2190 en eenmaal als 2190_mp

**Comment by ToonHub** [comment]
> IV2022051115125222 en IV2022051309464011: oppervlakte toevoegen (1018)
>IV2022032109305197 verwijderen (user reference = 8207669)

OK

**Comment by ToonHub** [comment]
> plot 11686065 is dubbel ingevoerd (zowel cirkel als vierkante plot)
plot 4608177 is dubbel ingevoerd (zowel cirkel als vierkante plot), eenmaal als 2190 en eenmaal als 2190_mp

nog steeds dubbel

**Comment by ToonHub** [comment]
Ook voor plot 414646, 4608177, 905382 dubbele invoer van cirkelplot

**Comment by Patrikoosterlynck** [comment]
Alles in deze issue is opgekuist. De dubbels die er nu nog inzitten zijn hermetingen (zie datum)
