### ISSUE TITLE
opgemeten meetpunten die niet in inboveg zitten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#3]
In bijlage een overzicht van meetpunten waarvoor aangegeven wordt dat ze vóór 2019 werden opgemeten, maar die nog niet in INBOveg zitten. Hierdoor is het geobserveerde habitat nog onbekend.

[check_not_in_database.txt](https://github.com/inbo/n2khab-sample-admin/files/4358562/check_not_in_database.txt)

**Comment by Patrikoosterlynck** [comment]
De OKs zouden nu wel in de survey moeten zitten
De 'zit in survey' zitten weldegelijk in INBOVEG, en ik kan die ook in R ophalen
De 'niet in survey' ontbreken weldegelijk, ik vraag na bij de veldwerkers of hier nog kan aangevuld worden


908981_1330_hpr   908981 "1330_hpr" 2016 FALSE | ok
783954_6230_ha 783954 "6230_ha"   2016 FALSE | zit in survey
311262_6230_hn 311262 "6230_hn"   2016 FALSE | zit in survey
783954_6230_hn 783954 "6230_hn"   2016 FALSE | zit in survey
1132201_7140_meso 1132201   "7140_meso" 2017 FALSE | niet in surveys, navragen
1404382_7140_oli 1404382   "7140_oli" 2017 FALSE | niet in surveys, navragen
1465330_7140_oli 1465330   "7140_oli" 2017 FALSE | niet in surveys, navragen
1750129_1330_hpr 1750129   "1330_hpr" 2018 FALSE | ok
1947634_7140_oli 1947634   "7140_oli" 2018 FALSE | niet in surveys, navragen

**Comment by Patrikoosterlynck** [comment]
Afgewerkt:
niet in survey: 1132201_7140_meso 1132201 "7140_meso" 2017 FALSE: ok ingevoerd
niet in survey: 1404382_7140_oli 1404382 "7140_oli" 2017 FALSE: ok ingevoerd
niet in survey: 1465330_7140_oli 1465330 "7140_oli" 2017 FALSE : data kwijt: geschrapt in overzicht, te bezoeken in 2020
1947634_7140_oli 1947634 "7140_oli" 2018 FALSE | niet in surveys, navragen: data kwijt: geschrapt in overzicht, te bezoeken in 2020

ik bezorg je nog een nieuw overzicht waarin de laatste twee meetpunten geschrapt zijn

**Comment by Patrikoosterlynck** [comment]
issue mag toe?

**Comment by ToonHub** [comment]
bovenstaande nagekeken in R en OK!

Nu ook meetpunten duinen nagekeken: en data in INBOveg ontbreekt nog voor volgende meetpunten: 10481457_2130_hd, 10481457_2170, PINK_pd_04, 10119985_2160, 11923249_2170, 12873521_2170, 11824945_2170, 11071281_2190, 10809137_2190, 12431153_2190

@Patrikoosterlynck , kijk je nog eens na.

**Comment by Patrikoosterlynck** [comment]
zijn volgens mij nog inet ingevoerd, ik vraag na

**Comment by Patrikoosterlynck** [comment]
Toon, die PINKpd_04 kan ik niet thuisbrengen? Welke codering gebruik jij? Kan je me een rankingnr bezorgen?

**Comment by ToonHub** [comment]
De PINK PQ met ranking 1011505

**Comment by Patrikoosterlynck** [comment]
10481457_2130_hd: ontbreekt
10481457_2170: ontbreekt
PINK_pd_04 (1011505): ontbreekt
10119985_2160: ontbreekt
11923249_2170: zit erin als 11923249_2190_mp
 12873521_2170: ontbreekt
11824945_2170: ontbreekt
 11071281_2190: zit erin als 11071281_2190_mp
10809137_2190: zit erin als 10809137_2190_mp
12431153_2190: zit erin als 12431153_2190_mp

**Comment by Patrikoosterlynck** [comment]
ik kijk de ontbrekende nog na of die nog aan te vullen zijn!
