### ISSUE TITLE
twee opnames in INBOVEG voor hs_04, hs_05, hs_12 en hs_13

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#30]
Voor de meetpunten met referentie hs_04, hs_05, hs_12, hs_13 en 514225 zijn er steeds twee opnames:

- op 2020-08-19 (in de user referentie wordt HS dan met hoofdletters geschreven)
- op 2021-08-19 (in de user referentie wordt hs dan met kleine letters geschreven)

Gezien er net een jaar tussen de twee opnames zijn, gaat het mogelijk om een fout. In de voortgangstabel staan enkel de opnames in 2021 vermeld.

Bij hs_13 verschilt het geobserveerde habitattype op beide data.

Opnames uit 2020 verwijderen of als dubbels beschouwen?

Bij meetpunt 358577 is er op 2020-08-21 een opname gebeurd (zonder verschuiving) voor 2130 en op 2021-08-23 een opname met verschuiving voor 2120. Die van 2020 behouden?

**Comment by Patrikoosterlynck** [comment]
OK en aangepast zoals jij voorstelde, dubbels zijn met double_userref in inboveg geduid.
Het schijnt mij dat de opnames onafhankelijk van elkaar zijn gebeurd, en dit toevallig op dezelfde datum in opeenvolgende jaren
Kan nog nuttig zijn om ooit de waarnemermeetfout op te bekijken

**Comment by ToonHub** [comment]
ok
