### ISSUE TITLE
ontbrekende inboveg opnames voor meetpunten die volgens overzichtstabel werden opgemeten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#33]
Hier een tabel met opnames die ik niet terugvind in inboveg. Mogelijks moeten die van 2022 nog ingevoerd worden. Maar ik veronderstel dat die van 2021 al ingevoerd zouden moeten zijn. Enig idee? 

[missing_inboveg.csv](https://github.com/inbo/n2khab-sample-admin/files/11450381/missing_inboveg.csv)

**Comment by Patrikoosterlynck** [comment]
Toon,
heb nog niet gecontroleerd maar gros van deze opnames zit in een andere INBOVEG survey, mn ùsurveyN2000_Duinen_Fieldapp.
Deze is specifiek germaakt om via de INBOVEG app data in te voeren. De survey is ook wat anders opgebouwd de data zitten allemaal in één Classic opname dus geen subopnames meer in ketting + Classic formaat.
KDenk/hoop dat dat qua analyse hopelijk niet te veel problemen mag geven

**Comment by ToonHub** [comment]
OK. Normaal geen probleem. Ik zal het bekijken.
