### ISSUE TITLE
opname 673910 niet in INBOVEG

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#36]
voor meetpunt 673910 zou er een opname zijn gebeurd voor 7140_oli op 26-09-2022. Maar vind dit niet terug in INBOVEG.

**Comment by Patrikoosterlynck** [comment]
Mmm, idd, ik moet navragen bij opnamemaker, en die is tot oktober in verlof...
ik zet het in mijn to do lijst

**Comment by Patrikoosterlynck** [comment]
opname niet teruggevonden, punt als niet bezocht gemarkeerd in mhq

**Comment by ToonHub** [comment]
OK
