### ISSUE TITLE
opnames in INBOVEG die niet in voortgangstabel zitten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#37]
1381553,  7050417, wn_21, 2003969, 8557745

**Comment by Patrikoosterlynck** [comment]
OK, alles opgelost

1381553 is een id code en geen  userref: deze aangepast naar wn_5,
7050417 aangevuld in mhq tabel 
wn_21 aangevuld in mhq tabel
2003969 aangevuld in mhq tabel
8557745 aangevuld in mhq tabel
