### ISSUE TITLE
meetpunten die verschoven werden maar die geen doelhabitat bevatten

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#4]
In bijlage een overzicht van meetpunten die verplaatst werden maar toch geen doelhabitat bevatten (wel een ander graslandsubtype). Mag in principe niet volgens het protocol.  Begrijp niet op basis van welke criteria er in die gevallen een nieuwe locatie gekozen wordt. 

[check_position_change.txt](https://github.com/inbo/n2khab-sample-admin/files/4358594/check_position_change.txt)

**Comment by Patrikoosterlynck** [comment]
De redenering doelvegetatie is aanwezig is hier veelal gebeurd op niveau van het habitattype en niet op niveau van de subtypes. Dit is volgens mij te verantwoorden omdat de meetpunten voor het gros van de toepassingen geïntegreerd worden op niveau habitattype. In sommige is zelf tussen types (bv. 6230 en 6410)gewisseld maar habitattypes (en bij uitstek de schraalgraslanden) zijn niet altijd duidelijk  toe te kennen tot één type. Bediscussiëren hoe we verder mee omgaan. 
De redenering die gevolgd wordt is dat de initiële doelhabitat bepaald op basis van de kartering fout is en dat er dus voor het effectief aanwezige habitat gemeten zal worden, maar ook om dit te kunnen meten is de oorspronkelijke locatie verlegd. Hetzelfde probleem van verwisselen van doelhabitat zal je ook aantreffen bij niet verlegde plots trouwens.
