### ISSUE TITLE
meetpunten verplaatst en relocation = FALSE

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#41]
Hieronder een bestand met verplaatste meetpunten, maar waarvoor de tabel aangeeft relocation = FALSE

[check_coördinaten.csv](https://github.com/user-attachments/files/17476341/check_coordinaten.csv)

Twee meetpunten zijn verplaatst naar een aangrenzend hok (distance = 32 m). 
Andere meetpunten zijn verplaatst binnen het hok. Dus niet volgens protocol.

**Comment by Patrikoosterlynck** [comment]
Dag Toon,
ik heb de punten met afwijkende locatie gecheckt
Probleempjes zijn opgelost: drie gevallen waarbij de coords van de eerste meting in jouw sheet niet overeenstemmen met de coords in mijn bestanden. Ze zaten meestal ook niet correct in mhq-sheet dus aangepast nu.
Eentje waarvan ik niet weet waar je de coords van de hermetingen gehaald hebt???
Zie eventueel bijlage voor details
[check_coordinaten_2024_PO.csv](https://github.com/user-attachments/files/17491337/check_coordinaten_2024_PO.csv)

**Comment by ToonHub** [comment]
De coördinaten in INBOVEG gebruik ik als bron.
Op basis daarvan update ik de tabel (mhq_terr_refpoints) met de coördinaten van alle point_codes. 
Vroeger heb ik gebruik gemaakt van bestanden met coördinaten van opnames die je mij bezorgde, omdat toen nog niet alles in INBOVEG was ingevoerd.  

- 3_2: de aangepaste coördinaten in de google sheet komen overeen met deze in INBOVEG --> ik pas dit aan in mhq_terr_refpoints 
- 31_2: de aangepaste coördinaten in de google sheet komen niet overeen met deze in INBOVEG --> nog aan te passen in INBOVEG --> daarna ook aanpassen  in mhq_terr_refpoints
- 528582_2: OK, opgelost
- 89810_1: ik gebruikte voor de resurvey de coördinaten van de vierkante plot; die wijken (in INBOVEG) af van de coördianten van de cirkelplot --> gaan we er vanuit dat de coördinaten van de cirkelplot correct zijn?

**Comment by Patrikoosterlynck** [comment]
is de 'mhq_terr_refpoints' dezelfde googlesheet als '[voortgang mhq terrestrisch](https://docs.google.com/spreadsheets/d/1WkGPPYTb1Xytg5kJeOSxLvt3PUdFjlpPb4rwYG9znys/edit?usp=sharing)' ??
Zo ja:

- opnieuw of nog steeds een probleem voor 3_2 (coordinaten van de hermeting vallen niet samen met t0 in de sheet, wel in INBOVEG), ik zou hier dus in voortgang mhq terrestrisch aanpassen en voor meting 2023 dezelfde coordinaten als in 2019 gebruiken (dacht dat ik al gedaan had..). OK?  
- 31_2 zit in INBOVEG en voortgang mhq terrestrisch goed qua coords, aan mijn kant schijnt geen aanpassing meer nodig?
- 89810_1: coords van de vierkantplot zijn niet omgezet naar Lambert72 in INBOVEG mogelijk kwam het probleem van daar? Maar ik zou verwachten dat daardoor een zeer grote distance afwijking wordt veroorzaakt, Soit, ik heb de coords vd vierkantplot aangepast

**Comment by ToonHub** [comment]
Bovenstaande punten zijn opgelost.

Ook onderstaande punten nagekeken en OK:
[check_coördinaten.csv](https://github.com/user-attachments/files/17714826/check_coordinaten.csv)

**Comment by Patrikoosterlynck** [comment]
nagekeken en aangepast

**Comment by ToonHub** [comment]
De coördinaten van dp_03 zijn nog niet aangepast. De rest is OK.

**Comment by Patrikoosterlynck** [comment]
OKe heb de coords in INBOVEG aangepast, maar ik vind dus de verwijzing naar dp_03 nergens terug in mijn originele meetpunten, wel de ranking 999217 en point code 999217_1. Ik heb de db_ref (dp_03) dan ook aangepast naar 999217.
OK?

**Comment by ToonHub** [comment]
OK
