### ISSUE TITLE
meetpunten waarvoor subtype geobserveerd habitattype niet is vastgesteld

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#5]
Als subtype van geobserveerd habitattype ontbreekt, ga ik er vanuit dat het subtype overeenkomt met dat van doelhabitat. Maar in één geval komt het hoofdtype van het gebobserveerd habitattype niet overeen met dat van het doelhabitat en kan het subtype dus niet afgeleid worden. Zie Bijlage.

[check_subtype.txt](https://github.com/inbo/n2khab-sample-admin/files/4358629/check_subtype.txt)

**Comment by Patrikoosterlynck** [comment]
subtype kan toegekend worden op basis van soortenlijst en vegetatiesleutel (6410_ve). Eigenlijk moeten we maximaal afdwingen dat er tot op subtype wordt bepaald, hoewel dat in sommige gevallen in de sleutel ook onopgelost raakt ... bv bij 6410

**Comment by Patrikoosterlynck** [comment]
Patrik past aan in INBOVEG

**Comment by Patrikoosterlynck** [comment]
ok is aangepast, issue mag toe?

**Comment by ToonHub** [comment]
nagekeken in R en OK!
