### ISSUE TITLE
Twee mogelijke geobserveerde habitattypen voor locatie met grts-ranking 3276198

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#6]
Indien in de vegetatieplot meerdere habitattypen worden waargenomen, moet we een aanname maken over welk van deze habitattypen in het plotcentrum gelegen is. 
Ik ga er dan vanuit dat het geobserveerde habitattype in het plotcentrum overeenkomt met doelhabitat voor die locatie. Voor locatie met grts-ranking 3276198 zijn er 2 doelhabitats (6230_hn en 6230_hmo) en beide typen worden met 50% bedekking geobserveerd in vegetatieplot. Welke hiervan in het plotcentrum gelegen is, kan niet achterhaald worden. 
Belangrijk dat het habitattype in het plotcentrum in de toekomst expliciet genoteerd wordt!

**Comment by Patrikoosterlynck** [comment]
Deze plot is opgenomen in 2016. Het betreft schijnbaar een locatie die moeilijk tot het ene of ander subtype kan toegekend worden en om die reden zijn er twee types gebruikt.
Er is echter ondertussen de afspraak om niet op zo'n manier te werk te gaan (overgangssituatie behoren tot de doelvegetatie) en zeker niet op niveau van de 3x3 plot. We kunnen hier op basis van de regels uit de determinatiesleutel aanpassen naar één van beide subtypes. Maar akkoord om in de toekomst het habitattype in het plotcentrum te noteren ter controle.

**Comment by Patrikoosterlynck** [comment]
Patrik geeft door welk subtype het betreft voor het specifieke geval en past aan in INBOVEG

**Comment by Patrikoosterlynck** [comment]
Ok is opgelost in INBOVEG (vegetatieplot 100% 6230_hmo)
Issue mag toe

**Comment by ToonHub** [comment]
nageken in R en OK!
