### ISSUE TITLE
Meetpunten waarvoor vegetatiegegevens of structuurgegevens ontbreken

### ISSUE THREAD

**Issue by ToonHub** [inbo/n2khab-sample-admin#9]
Voor sommige cirkelplots ontbreken de structuurgegevens. Voor enkele cirkel- of vierkante plots ontbreken de vegetatiegegevens.

[check_plots_data_import.txt](https://github.com/inbo/n2khab-sample-admin/files/4403011/check_plots_data_import.txt)

**Comment by Patrikoosterlynck** [comment]
"1" "N2000meetnet_Grasland" "IV2017010910225147" "circle" "2015-05-27" "500782" TRUE FALSE TRUE "500782"  geen veg_Rec voor cirkel
"2" "N2000meetnet_Moerassen" "IV2017022111070389" "circle" "2015-08-18" "996278" TRUE FALSE TRUE "996278" geen veg_Rec voor cirkel (ontoegankelijk moeras)
"3" "N2000meetnet_Grasland_BHM" "IV2019010314291141" "circle" "2018-06-28" "1338805" TRUE FALSE TRUE "1338805"geen veg_Rec voor cirkel (ontoegankelijk moeras)
"5" "N2000meetnet_Grasland_BHM" "IV2019031509012165" "circle" "2018-06-27" "3351638" TRUE FALSE TRUE "3351638" geen veg_Rec voor cirkel
"6" "N2000meetnet_Duinen_BHM" "IV2019022013422931" "square" "2018-09-27" "10578737_2120" TRUE FALSE NA "10578737" vegetatieloos duin
"7" "N2000meetnet_Duinen_BHM" "IV2020031623341355" "square" "2019-10-15" "10342193_2120" TRUE FALSE NA "10342193" vegetatieloos duin

**Comment by Patrikoosterlynck** [comment]
enkele punten betreft vegetatieloos duin (staat als naakte bodem 100% in de databank) en voor de andere is telkens in INBOVEGcommentaren een uitleg voorzien waarom de vegetatiegegevens ontbreken voor de cirkels (meestal te maken met moeilijke betreedbaarheid, overzichtelijkheid)
